### ISSUE TITLE
Is there any reason that you use sample without replacement?

### ISSUE THREAD

**Issue by jseongpark** [grf-labs/grf#1121]
Dear Dr. Tibshirani and grf R package team,

Hello! I am looking at cpp files in your grf package.
It seems that random forest building in package grf is based on sample without replacement in tree building.
However, based on my knowledge of random forest,
the tree building should be based on sample with replacement (nonparametric bootstrap).
Is there any reason that you use sample without replacement?

Thank you!

**Comment by erikcs** [comment]
Hi @jseongpark, GRF uses random forests to obtain some parameter estimates &tau;(x) given by the solution to a forest weighted estimating equation &psi;. The estimates of &tau;(x) are consistent under some assumptions on the forest construction scheme as detailed in the [GRF paper](https://arxiv.org/abs/1610.01271) and subsampling is one of the ingredients. Why subsampling: the aforementioned result relies on large sample behavior. It turns out characterizing this large sample behavior if we allow some duplicate samples (as the bootstrap would do) is very tricky, and which subsampling avoids completely. Turning to subsampling when analyzing random forests is quite standard, section 4.1 in https://arxiv.org/abs/1511.05741 even has a paragraph on it.

**Comment by erikcs** [comment]
Just tacking on another reference that gives intuition on the choice of subsampling instead of resampling: section 3.1 second to last paragraph in https://arxiv.org/pdf/1510.04342.pdf
