### ISSUE TITLE
Calculating risk ratio under continuous treatment setting. 

### ISSUE THREAD

**Issue by yujias424** [grf-labs/grf#1180]
Hi

I wonder whether it is possible to calculate the risk ratio under a continuous treatment/binary outcome setting. I know it is easy to obtain the risk ratio under binary treatment; we can follow https://grf-labs.github.io/grf/articles/muhats.html, as discussed in #720. Any hints would be helpful!

Thanks!

**Comment by erikcs** [comment]
Hi @yujias424, do you have reference where a risk ratio under continuous treatment is defined? (that's not something I've come across before).

If you just want something analogous to E[Y(0)|X] and E[Y(1) | X]  for continuous treatment, you could look at https://arxiv.org/pdf/1702.02896.pdf (8) where they implicitly define the "reward" for subject i as the the expected increase in Y from increasing W by a tiny amount. They have a worked example of estimating that in section B, but since it involves estimating smooth derivatives they don't use GRF.

**Comment by yujias424** [comment]
Hi Erik @erikcs, Sorry for the late reply. 
For the RR under continuous treatment, I think this paper could be a reference (https://doi.org/10.48550/arXiv.1906.00558), where RR(z0, z; v) = Pr(Y = 1 | V = v, Z = z)/Pr(Y = 1 | V = v, Z = z0). The z0 is a baseline treatment, v is a random vector of covariates. 
I'll first check the paper you mentioned to see whether it could solve the problem.
Thank you!

**Comment by erikcs** [comment]
Ok, you could use grf's regression_forest to estimate P[Y = 1 | V, Z] then plug in and divide. I.e. `rf = regression_forest(cbind(V, Z), Y); p.hat.z0 = predict(rf, cbind(X, z0))`
