### ISSUE TITLE
ranger() v.s. regression_forest()

### ISSUE THREAD

**Issue by tmieno2** [grf-labs/grf#1182]
Hi team,

I was working out the math for regression forest (RF) under the GRF framework to just have myself understand how GRF works better, and I encountered a question I would like to ask.

In general, the weight given to observation $i$ is 

![CodeCogsEqn](https://user-images.githubusercontent.com/13700450/178005118-814fae4f-c2ec-4d06-862f-d09f5b273737.svg)

where $\eta_{i,t}(X)$ is 1 if observation $i$ belongs to the same leaf as $X=x$ in tree $t$, and $T$ is the total number of trees. 

Solving 

![CodeCogsEqn (2)](https://user-images.githubusercontent.com/13700450/178005784-fb815a98-bbf4-4faa-a7cd-76aa64b3ded3.svg)

After some rearranging, I got 

![CodeCogsEqn (3)](https://user-images.githubusercontent.com/13700450/178005953-17053fdf-1497-48b4-81e3-6fa9bf1ca2ca.svg)

where $N_t$ is the number of observations in the same leaf that $x$ belongs to. 

And, $\bar{Y}_t$ is the mean value of $Y$ in the leaf.

So, the `grf` implementation of RF seems to be using weighted (by sample size in the leaf) average of the predictions from the trees, which I think is consistent with what's written below on the `grf` package website (by the way, I believe $\alpha \times Y$ for $X_1$ and $X_4$ should be 1.6 instead of 0.8, and final prediction is 3.6).

<img width="871" alt="Screen Shot 2022-07-08 at 9 14 37 AM" src="https://user-images.githubusercontent.com/13700450/178010436-0601f187-2156-4015-a59f-b9fde1436855.png">

Since a traditional implementation of RF just averages the prediction from each tree like below

![CodeCogsEqn (4)](https://user-images.githubusercontent.com/13700450/178006801-f13f061a-52b7-497b-b9be-3a6fa678347c.svg)

this difference in averaging results in different predictions even if the `grf` and `ranger` implementation happens to build exactly the same trees, right? This distinction probably makes a very little difference in practice. But, I would appreciate it if you could confirm this for a peace of my mind and also for avoiding teaching my students something wrong.

**Comment by erikcs** [comment]
Hi @tmieno2,

For a regression forest, GRF's method and a the "traditional" method gives the exact same predictions, as you said (there's a comment on this at the end of 2.1 in https://arxiv.org/abs/1610.01271)

In practice, yes, you can just attribute the prediction differences to numerical fuzz (remember in the world of numerical computing even the simplest operations might not give the same answer, such as computing a sum in different chunks). Also, just getting grf and ranger to build the exact same trees with the correct config options would also likely be very hard, for the same reason + random forest's discontinuous nature: if a single split differs by just some epsilon (which is perfectly feasible since the implementations are different) the resulting tree will be different.

(and yes, that was a typo, thanks!)

**Comment by erikcs** [comment]
Btw, here's a simple example in R that might make you feel more comfortable ascribing small differences to the vagaries of numerics:

```R
options(scipen = 9999)
a = 1e-8
b = 1e-8
c = 1e-8
d = 1e8

sum1 = a + b + c + d
sum2 = d + a + b + c

sum1 - sum2
# [1] -0.00000001490116
```

**Comment by tmieno2** [comment]
Hi @erikcs, thanks for this!

**Comment by erikcs** [comment]
@tmieno2: I just recalled that you may have been using the above Table example for teaching purpose. It actually had another mistake (#1251), it's correct now (sorry about that, my brain must have been on vacation when writing that paragraph).

PS:  on teaching note, we just made [this vignette](https://grf-labs.github.io/grf/articles/grf_guide.html) that covers some of the statistical details behind grf, it may still be a bit terse, but could serve as giving a broad overview of the statistical underpinnings of causal forest.
