### ISSUE TITLE
Question for Causal Survival Forest Paper

### ISSUE THREAD

**Issue by chenx2018** [grf-labs/grf#1439]
Dear all,

Thank you for the outstanding work on the `grf` package and the insightful paper, "Estimating Heterogeneous Treatment Effects with Right-Censored Data via Causal Survival Forests" (Cui et al., 2023).

I have a question regarding the intuition behind equation (9) in the paper:

![Screenshot 2024-09-01 at 08.46.36](https://cdn.jsdelivr.net/gh/chenx2018/blogdown-image@main/uPic2/Screenshot%202024-09-01%20at%2008.46.36.png)

My current understanding is as follows:

- The first term represents non-censored events, weighted by the inverse of the survival probability at the censored survival time or threshold $h$. 
- The second term adjusts for censored observations by incorporating the expected score beyond the censored survival time.
- However, I’m having difficulty understanding the intuition behind the third term, particularly since I am not familiar with survival analysis.

Could you please provide the underlying intuition or rationale for eqn (9)?

Thank you for your time and for developing such a valuable tool!

**Comment by erikcs** [comment]
Hi @chenx2018, the rationale for eqn (9) is to leverage doubly robust estimating equations when estimating $\tau$. For right-censored data with continuous censoring, it turns out that the efficient influence function takes that general form. [Rubin & van der Laan (2007)](https://www.degruyter.com/document/doi/10.2202/1557-4679.1052/html?lang=en) and the chapter on RCTs with time-to-event data in [Targeted Learning (2011)](https://link.springer.com/chapter/10.1007/978-1-4419-9782-1_17) gives some more digestible details on doubly robust estimation with survival data than the Tsiatis book referenced in the paper by considering the simpler concrete problem of estimating a survival probability.

**Comment by erikcs** [comment]
By the way, @chenx2018, your blog here https://chenxing.space/blog/ is very nice, great work!

**Comment by chenx2018** [comment]
Thanks for the explanation! I’ll take a look at the resource you recommend, they sound helpful. And I’m glad you liked my blog, that made my day!
