### ISSUE TITLE
Create a way to train and predict from C++.

### ISSUE THREAD

**Issue by jtibshirani** [grf-labs/grf#271]
It would be great if there was a command-line interface that allowed for training a forest + making predictions entirely from C++. As a reference, it may be useful to look at how this is implemented in ranger (https://github.com/imbs-hl/ranger#standalone-c-version).

**Comment by halflearned** [comment]
I've been playing around with command-line interfaces, and I've got a simple, crude prototype working over [here](https://github.com/halflearned/grf/blob/argparser/core/xcode/xcode/main.cpp). It only works with `regression_forest`, because any other forest type needs nontrivial computations in R. The argument parsing implementation uses the "lightweight, header-only" library [cxxopts](https://github.com/jarro2783/cxxopts). 

The current API vaguely follows`ranger`. Examples: 

+ To train a forest on `data.csv`, save the serialized forest in `output.forest`
```
./grf --input_file "/path/to/data.csv" --outcome_index=0  --write output.forest 
```

+ To additionally predict and save the predictions in `predictions.csv`:
```
./grf --input_file "/path/to/data.csv" --outcome_index=0  --write output.forest --output_file predictions.csv 
```

+ To load a previously saved forest and predict (without training)
```
./grf --input_file "/path/to/data.csv" --outcome_index=0  --load output.forest --output_file predictions.csv 
```

+ To train with specific parameters
```
./grf --input_file "/path/to/data.csv" --outcome_index=0  --write output.forest --num_trees=2000 --alpha=0.25 --num_threads=1 --min_node_size=35
```

Again: it's just a prototype. I mainly use it to be able to benchmark functions without using R. 

+ How much do we like the API above? 
+ Should we implement `causal_forest` as well? (This involves porting the R bits to C++)

**Comment by Lirunhua** [comment]
Should we implement causal_forest as well? 
-- YES!!

**Comment by halflearned** [comment]
Hi @Lirunhua! Actually, this issue had in mind an earlier version of grf, in which there were still several benefits from bypassing R both in terms of performance and memory requirements. But our latest version is does a better job handling the C++ interface, so to our knowledge these benefits are small. But I'm curious -- why would accessing grf through C++ directly be convenient for you?

**Comment by halflearned** [comment]
We had two reasons for this interface. First, to avoid some performance loss when translating between R and C++. Some of this has been addressed (e.g., #187, #408), and more work on this is being done (e.g., #598). Second, to avoid having recompilation during the development process when updating the C++ code. This has been taken care of in #440.
