### ISSUE TITLE
Support for adding more trees to a trained forest.

### ISSUE THREAD

**Issue by jtibshirani** [grf-labs/grf#272]
A user may train a forest, then realize that more trees are needed (for better predictions, tighter confidence intervals, etc.) Instead of starting from scratch and training a completely new forest, it would be great if the user was able to grow some number of additional trees, and add these trees to the original forest.

Proposal for the API: each forest method (`regression_forest`, `causal_forest`, etc.) can take in an optional parameter `existing.forest` (or something similar). The final forest will contain trees from the original forest, as well as newly grown trees. The methods should error if the provided forest isn't of the correct type.

It would also be interesting to experiment with using this functionality during tuning: if parameters haven't changed too much, we could include the trees used for tuning when creating the final forest, and so need to grow fewer trees in the final training step. I think it would be misleading to do this by default, but may be interesting to explore as part of an 'optimized' option.

**Comment by susanathey** [comment]
If we want to parallelize building a forest in a large dataset (parallelize across machines, for example), which seems like a common scenario for larger datasets and a natural one since the forest routine is naturally parallelizable, it would be important that we can union forests rather than take in an existing forest and add to it.  Can I suggest creating a union function, and then if we want you can do as you suggest above, but that would call the union function?

**Comment by jtibshirani** [comment]
I was initially hesitant to go with a `union` function, because in the common case of adding more trees to an existing forest (on a single machine)
- there would be an extra round of serialization between C++ and R, which we know to be expensive
- now that we include OOB predictions by default as part of training, a `union` method would need to rerun OOB prediction, which is also wasteful

The use case around combining forests makes a lot of sense, though -- I'd be happy to support both in R (and still share quite a bit of common merging code under the hood in C++).

**Comment by halflearned** [comment]
In #347 I submitted a first attempt at this. As it turns out, the basic functionality was easy to implement. A basic example looks like

```{r}
rf1 <- regression_forest(X, Y, num.trees=100, compute.oob.predictions=FALSE) # OOB preds will be ignored anyway
rf2 <- regression_forest(X, Y, num.trees=100, compute.oob.predictions=FALSE)
big_rf <- join_forests(list(rf1, rf2))  # Has num.trees = 200
```
The syntax is the same regardless of the forest type.

Some considerations:

1. As @jtibshirani commented above, forest concatenation happens on the C++ side, so to concatenate R-side forests we need an extra round of serialization.

2. I believe we'd like to help the user who has a dataset so large that it can't be used at once in memory, so they choose to grow forests on small subsamples of the original dataset and concatenate them at the end. But we currently do *not* support this functionality with OOB predictions, because we are not keeping track of each observation's indices in the original dataset.

3. I wrote a minimum validation function, ensuring that forests need to be of the same type. Do we want to be stricter and and force the user to have fit forests with the same hyperparameters?

**Comment by susanathey** [comment]
I don't think we want the same hyperparameters to be forced because people may want to save forests while tuning.  We DO need to figure out a way to support OOB predictions.  Perhaps we want to support an optional column variable in the dataset which is the master index of the observation?

**Comment by jtibshirani** [comment]
We discussed the API offline, and decided to stick with a single union/ merge method for now. We've been working on lowering the cost of serialization (#187), which will address my main concern around the 'union' approach.

@halflearned added a `merge_forests` method #347, so I'm closing this as 'done'. I suggest that we track ideas around sharding the data in #90.
