### ISSUE TITLE
Out-of-bag predictions at arbitrary X's

### ISSUE THREAD

**Issue by tcovert** [grf-labs/grf#307]
Suppose I estimate a `regression_forest` with matrices `Y` and `X`, and I construct a matrix of the same shape as `X`, call it `Z`, but with possibly perturbed values.  Is it possible to recover `E[y|X = z_i]`where the prediction is taken over all trees that did not use observation `i` in training? This is similar to what the standard `predict` routine does when you don't pass it a `newdata` matrix, but not quite the same, I don't think.

For reference, my use case here is pretty similar to the `causal_forest` setup.  I have a treatment effects setup in mind, but instead of computing `E[Y1|X]-E[Y0|X]` I'd like to do something like `log(E[Y1|X])-log(E[Y0|X])`, and my goal is to construct these conditional expectations in a somewhat "honest" fashion.

Thanks in advance for any ideas on how to do this in the existing package, or for consideration of adding this feature if it is not currently possible.

**Comment by jtibshirani** [comment]
Hi @tcovert, thanks for the issue! From what I understand, after training a forest you'd like to essentially 'swap out' the training data matrix with a new one of the same shape, and use this when making OOB predictions. This is not an option we currently support, as it's not a workflow we've commonly come across.

However, I can suggest a hacky workaround that may be enough for your current needs. Given a trained forest called `forest`, you can modify this R object in the following way:
- Set `forest$X.orig = Z`, where `Z` is your new perturbed data matrix. This essentially tells the forest to use `Z` when computing OOB predictions, as opposed to the original training data.
- Set `forest$predictions = NULL` and `forest$debiased.error = NULL`. We calculate OOB predictions and error estimates during training, and cache them in the forest for efficiency. This will clear out those cached values, so that you're able to run OOB prediction on the new matrix.

Then, you can run OOB prediction as normal through `predict(forest)`, and it should use `Z` instead of the original `X`.

This approach should work with recent versions of the package (as of this writing, the current version is `0.10.11`). Unfortunately, it relies on some internal implementation details that may change in future versions of the package.

**Comment by jtibshirani** [comment]
I'm going to close this, but please feel free to reopen it (or file another issue) if this didn't address your question.
