### ISSUE TITLE
What is the relationship between M5/Cubist and grf Local Linear Forests?

### ISSUE THREAD

**Issue by kendonB** [grf-labs/grf#315]

**Comment by rinafriedberg** [comment]
Hey @kendonB ,

This is a great question! To my understanding, the M5/Cubist model grows a tree and predicts by averaging the results of linear regressions in each leaf. This is still an 'average of trees' method, but instead of averaging means from each leaf, it averages regression predictions from each leaf. 

On the other hand, grf/local linear forests use the trees to generate weights that are then plugged into a global local linear regression. This methods views forests as methods of solving locally weighted estimating equations, instead of as averaging leaf predictions, and correspondingly entails a different prediction method. More details on this algorithm specifically can be found [here](https://arxiv.org/pdf/1807.11408.pdf).

**Comment by kendonB** [comment]
Thanks!

**Comment by susanathey** [comment]
Approaches that build models within leaves require large leaves.  The grf/local linear forests can use smaller leaves and thus more local neighborhoods.  When weights are averaged across many trees, a larger number of unique data points can be considered in the final local regression at each point.
