### ISSUE TITLE
"overlap" in average treatment effects

### ISSUE THREAD

**Issue by tcovert** [grf-labs/grf#375]
The code for the `target.sample = "overlap"` option in `average_treatment_effects` seems to define the overlap weighted ATE as the coefficient on `W - E[W|X]` in a regression of `Y - E[Y|X]` on `W - E[W|X]` and a constant.  I'm guessing this is not a bug, but I don't see the direct link between this formulation, and the direct formula in Li, Morgan and Zaslovsky, which takes the familiar weighted average of outcomes form.  I did not see a derivation of this solution in the "GRF manual" or in the original two GRF-style papers.  Is the equivalence of these forms obvious?  If its not obvious, what reference should I review to understand how it works?

Thanks in advance, both for a possible answer to this question, and for writing this great package!

**Comment by swager** [comment]
I'm afraid this falls under the category of "well known" facts that aren't really clearly explained everywhere. Very informally... to see the connection, suppose that e(x) = P[W|X=x] and m(x) = E[Y|X=x] are known, and recall that under unconfoundedness we can write Yi = m(Xi) + (Wi - e(Xi)) tau(Xi) + "noise". Then, the residual-on-residual OLS estimator is

\hat{tau} = sum (Wi - e(Xi)) (Yi - m(Xi)) / sum (Wi - e(Xi))^2
= sum (Wi - e(Xi))^2 tau(Xi) / sum (Wi - e(Xi))^2 + "noise"

Finally, because E[(Wi - e(Xi))^2 | Xi = x] = e(x) (1 - e(x)), we can check convergence of the sums in the numerator and the denominator and find that

\hat{tau} -> E[e(X) (1 - e(X)) tau(X)] / E[e(X) (1 - e(X))].

You may also find Section 5 of this paper helpful, https://www.nber.org/papers/t0330.pdf. For more background on Robinson's transformation and a review of recent results, see https://arxiv.org/pdf/1712.04912.pdf.

**Comment by tcovert** [comment]
That was super clear, thanks!
