### ISSUE TITLE
How to calculate total effect in case of overlap based weights?

### ISSUE THREAD

**Issue by kingsharaman** [grf-labs/grf#377]
By total effect I mean the sum of individual effects. In case of ATT it would be ATT multiplied by the number of treated units. But by what should I multiply in case of `target.sample = "overlap"`? My goal is to somehow communicate the expected gain from a potential intervention when comparing interventions along different variables with different overlap.

**Comment by swager** [comment]
One negative aspect of the "overlap" weighted treatment effect is that it does not correspond to the effect of any standard policy intervention. In order to estimate the total effect of the treatment as it was actually deployed, I'd just use the ATT. In comparison, the overlap weighted treatment effect measures something like: what would be the effect of a policy where now I treat people with covariates X with probability e(X) * (1 - e(X)).
