### ISSUE TITLE
computation time with and without cluster specified 

### ISSUE THREAD

**Issue by ZhangMengxia** [grf-labs/grf#393]
I am trying specifications with and without specifying clusters for the causal_tree function, with the same dataset.

It seems when clusters are specified, the computations time (for causal_tree and average_partial_effect together) is shorter. Is this right?

I checked the "Cluster‑Robust Estimation" section of the reference. It seems to grow each tree, fewer samples are used when clusters are specified, because a subsample of clusters are first drawn for each tree. Not sure whether my understanding is correct.

Thanks a lot!

**Comment by swager** [comment]
It's not obvious to me that specifying clusters should in general make computation faster, although it may do so on some datasets. (In particular, running causal forest such that each observation gets its own cluster amounts to the same as not using clusters at all.)

In some cases, if you have very unevenly sized clusters, then clustering may make a difference, because by default each tree randomly downsamples big clusters until they look like small clusters (so we don't overemphasize big clusters). Section 1.2 of https://arxiv.org/pdf/1902.07409.pdf has further discussion of this.

**Comment by ZhangMengxia** [comment]
@swager Thanks a lot for your answer. The  reference looks very useful. I will dig into it.
