### ISSUE TITLE
test_calibration differential.forest.prediction p-value very often significant 

### ISSUE THREAD

**Issue by bakered** [grf-labs/grf#396]
**Description**
When there is no heterogeneity in the treatment effect, the differential.forest.prediction comes out highly significant. e.g. in the code below significant at 0.05 33% of the time.

**Steps to reproduce**
```
n = 800; p = 5; alpha = 0.05
sim<-vector(length=100)
for(s in 1:100){
  X = matrix(rnorm(n*p), n, p)
  W = rbinom(n, 1, 0.5)
  Y = W*5
  forest = causal_forest(X, Y, W)
  sim[s]<-test_calibration(forest)[2,4]<alpha
}
table(sim)
```

**GRF version**
Version 0.10.2

**Comment by swager** [comment]
Very interesting, @bakered, thanks for sharing. I tried replicating a closely related simulation (with some noise to make sure we're not hitting a zero-noise pathology), and got 26% rejections. Now what's curious is that the z-values for the heterogeneity coefficient are systematically negative. And, of course, with a properly calibrated forest we'd want the coefficient `differential.forest.prediction` to be positive, and preferably close to 1.

As a short-term fix, it might be helpful to consider using one-sided p-values in the `test_calibration` function (since, really, we're hoping to find positive, rather than non-zero, coefficients). Beyond that, it'd be super interesting to get a deeper understanding of what's going on. If anyone has clean formal results -- ideally that work for leave-one-out cross-fitting as is most computationally practical with forest -- please chime in!

```
n = 800; p = 5
zvalue = replicate(1000, {
    X = matrix(rnorm(n*p), n, p)
    W = rbinom(n, 1, 0.5)
    Y = W*5 + rnorm(n)
    forest = causal_forest(X, Y, W)
    test_calibration(forest)[2,1]
})
```

![image](https://user-images.githubusercontent.com/1275702/56253102-dd2f1f00-606f-11e9-83f1-25b84fad77fe.png)

**Comment by ras44** [comment]
Using the suggestion from @swager, running the following produces a false positive rate within the 5% as set by alpha:

```
n = 800; p = 5; alpha = 0.05
sim<-vector(length=100)
for(s in 1:100){
  X = matrix(rnorm(n*p), n, p)
  W = rbinom(n, 1, 0.5)
  Y = W*5
  forest = causal_forest(X, Y, W)
  tc <- test_calibration(forest)
  sim[s]<-tc[2,4]<alpha & tc[2,1]>0
}
table(sim)
```

If this is the correct treatment, perhaps the `test_calibration` function [description](https://github.com/grf-labs/grf/blob/17bddbc1790c33588b87ed8e72669954df1957ea/r-package/grf/R/forest_summary.R#L9-L12) should consider reading:

```
... If the coefficient is also significantly *greater than* 0, we can reject the null of no heterogeneity...
```

**Comment by swager** [comment]
Cool, thanks! It seems like we should make this change. One hiccup: it doesn't appear that the `coeftest` function used in `test_calibration` outputs regression tables for one-sided hypothesis tests. Does anyone know of an alternative package for printing summaries for robust inference that does so?

**Comment by ras44** [comment]
Could it be an option to modify what is returned from coeftest and output half the p-value that results from https://github.com/cran/lmtest/blob/518ee43f60e85de543b684490b969117837c3ec8/R/coeftest.R#L38, with the associated name 'Pr(>t)'?

**Comment by swager** [comment]
That sounds like a good option. Want to open a PR where we can discuss implementation details?

**Comment by ras44** [comment]
Sure! I've included two commits in the following PR: https://github.com/grf-labs/grf/pull/410

**Comment by swager** [comment]
Closing this issue for now, as using one-sided p-values appears to fix the most urgent problem. Happy to talk about this more, though, if anyone has thoughts about how to make calibration function better.
