### ISSUE TITLE
Add cobalt-style balance plots to causal forests

### ISSUE THREAD

**Issue by ZhangMengxia** [grf-labs/grf#420]
For propensity score matching, there are some ways to test whether the samples are indeed matched well.

Are there similar methods to exam the quality of matching for the causal forest?

Thanks a lot for your time!

**Comment by davidahirshberg** [comment]
Hi Mengxia,

What I recommend is checking by simulation. Given your observed covariates X_1...X_n and treatment assignments W_1...W_n, simulate potential outcomes Y_1(0)...Y_n(0) and Y_1(1)...Y_n(1) from some model P(Y(0),Y(1) | X) and let Y_1...Y_n = Y_1(W_1)...Y_n(W_n). Then fit the causal forest to your data (W_1,X_1,Y_1)...(W_n,X_n,Y_n) and check your results against the simulated treatment effect
(1/n)sum_i Y_i(1) - Y_i(0).  If you do this for a set of models for P(Y(0), Y(1) | X) that you believe contains a good approximation of the real conditional distribution, and the method works well for all of them, you have evidence that your estimator should work well.

Balance checks for propensity score matching and inverse propensity weighting methods are essentially just doing this.  If the unconfoundedness assumption holds, the error of an inverse propensity weighting estimator (1/n)sum_i Y_i W_i/e(X_i) for the average treatment effect is 
(1/n)sum_i m(X_i,1) - W_i/e(X_i) m(X_i,1) +   (1/n)sum_i m(X_i,0) - W_i/e(X_i)) m(X_i,1) 
+ (1/n)sum_i [W_i/e(X_i) +(1-W_i)/(1-e(X_i))] (Y_i - m(X_i,W_i))^2 where m(x,w) = E[Y(w) | X=x].
If we show, for example, that all covariates are balanced, i.e., that
(1/n)sum_i X_{i,j} - W_i/e(X_i) X_{i,j} and (1/n)sum_i X_{i,j} - W_i/e(X_i)) X_{i,j} 
are small, we've shown that the first two terms in this error decomposition are small for linear outcome models m(x,w) --- this is usually our main concern, because the last term in that error decomposition has mean zero and therefore does not contribute to bias. Other common balance checks, e.g. those based on Kologorov Smirnov tests on the marginals, correspond to certain nonlinear outcome models. 
So this is, in essence, a simplified version of checking by simulation based on assumptions about the outcome model m(x,w) = E[Y(w)|X=x]. We can get away with this simplified version with matching and weighting estimators because they use the outcomes Y_i  in a simple way.  Because our double-robust average treatment effect estimators use the data in a more complicated way, including a fit of a regression forest to E[Y | X=x], this shortcut doesn't work for us.

**Comment by ZhangMengxia** [comment]
@davidahirshberg Thanks a lot for your answer.
What if is the W is continuous?

**Comment by davidahirshberg** [comment]
It's harder. You can still simulate Y_1 ... Y_n from P(Y(W_1) | X_i=X_n) given a model P(Y(w) | X=x) and estimate an average partial effect, but what we'd want to compare to, (1/n)sum_i cov(Y(W_i), W_i | X=X_i) / var(W_i | X=X_i), requires us to know the distribution of W_i given X_i too.  What methods for checking the quality of propensity score ( e(x) = E[W|X=x] ) estimates are you thinking of in this setting?

**Comment by ZhangMengxia** [comment]
@davidahirshberg Thanks again! I don't know any. It would be great to have some sort of test so I can apply to each treatment variable. I have a lot of treatment variables in my case. Some are binary and some are continuous. I was worried some reviewer would ask me to justify how good the matching is.

**Comment by swager** [comment]
That's a good point. We should definitely add some automated balance checks to GRF. The standard balance check is something like they do in the R package <a href="https://cran.r-project.org/web/packages/cobalt/vignettes/cobalt_A0_basic_use.html">cobalt</a>, resulting in nice plots like this:

![image](https://user-images.githubusercontent.com/1275702/57986154-0b649d80-7a26-11e9-9d82-685ea8355ec2.png)

If the treatment is binary, one can just read off the propensities (`W.hat`) from the causal forest object, and make a plot exactly like the one above.

The remaining question then is, how can we get a standardized balance check that allows for a continuous treatment. One option is the following statistic to measure imbalance in the j-th feature:

```R
Ij = sum((W - W.hat) * (X[,j] - mean(X[,j])) / sqrt(sum((W - W.hat)^2)) / sd(X[,j])
```

Essentially, the first part of the expression is asking: If we regress the j-th feature on the propensity residual `W - W.hat`, what coefficient do we get? Then, we re-scale this by sd(X[,j]) to eliminate the units of X[,j]. Notice that this expression is also very closely related to Pearson's coefficient of correlation.

If anyone is interested in contributing balance plots of this type, please let us know!

**Comment by ZhangMengxia** [comment]
@swager thanks a lot for your super helpful answers!

I have two follow-up questions.

First, for a binary treatment, when I got the p.score = w.hat, shall I use the following equation to calculate the weight?
`att.weights <- with(dataset, treat + (1-treat)*p.score/(1-p.score))`

And then the following equation of cobalt to check balance?
`bal.tab(X, treat , weights = att.weights, method = "weighting")`

I am not sure how the weights for the causal tree should be calculated with the propensity scores.

Second, for the continuous treatment variable,

> Ij = sum((W - W.hat) * (X[,j] - mean(X[,j])) / sqrt(sum((W - W.hat)^2)) / sd(X[,j])

Once the above statistic is computed, how should I treat it? Is there a recommended threshold (above which indicates a bad matching)  or significance test?

Thanks a lot for your time!

**Comment by ZhangMengxia** [comment]
Another question is, W.hat can be specified or estimated outside the causal forest. In that case, the balance check is actually done before estimating a causal forest.

Is that right?

Thanks a lot!

**Comment by swager** [comment]
In response to your questions @ZhangMengxia:
- Yes those are good weights to use for the ATT
- I guess one could use 0.1 or 0.05 as a cutoff? But really the smaller the better. Note that the cobalt package actually discusses balance with continuous treatments (using the same statistic as discussed here), so it might be worth seeing if they have examples / guidance on this.
- Yes that's right -- as done here, the balance check only measures the quality of the propensity score estimates used in GRF (not the outcome fit).

**Comment by ZhangMengxia** [comment]
Thanks so much @swager !!

After a second look, I am wondering whether I should divide the following function by ![CodeCogsEqn (7)](https://user-images.githubusercontent.com/17790770/59644779-46401b00-9123-11e9-9a31-1fd70d42918c.gif). It seems the numerator is on the same scale of n, while the denominator is on the scale of ![CodeCogsEqn (7)](https://user-images.githubusercontent.com/17790770/59644791-56f09100-9123-11e9-9b9c-6c880a925c0b.gif)


`Ij = sum((W - W.hat) * (X[,j] - mean(X[,j])) / sqrt(sum((W - W.hat)^2)) / sd(X[,j])`

**Comment by swager** [comment]
Yes that's right

**Comment by ZhangMengxia** [comment]
@swager Thank you so much!! Really appreciate your help!

**Comment by ras44** [comment]
hi @swager, I had been reading through the cobalt documentation, but when I took a look at it today, I noticed the link in your [comment](https://github.com/grf-labs/grf/issues/420#issuecomment-493779357) is now broken.  Further, when I viist: https://cran.r-project.org/web/packages/cobalt/, it mentions that the package has been archived due to an unconditional dependency on WeightIt.  Any recommendations for how to proceed?  Thanks in advance!

**Comment by ras44** [comment]
hi @swager just pinging you on this- does the above look like it would be a show-stopper for this feature?  thanks in advance!

**Comment by swager** [comment]
Ah -- this is unexpected! Hopefully it should still be possible to install the package from source for prototyping purposes. But yes, this is an issue if we wanted to integrate more deeply with the package.

I think it still makes sense to first prototype so we have a set of plots we like, and then see how exactly we want to add that type of plots to GRF. For example, once we settle on how the plots should look, maybe we just implement them from scratch using ggplot.

**Comment by ras44** [comment]
Thanks for your feedback- will do!

**Comment by halflearned** [comment]
We don't have plans of implementing this feature in grf at the moment. Feel free to re-open if there's further interest in it.
