### ISSUE TITLE
regression_forest does not accept a data frame as X

### ISSUE THREAD

**Issue by swager** [grf-labs/grf#424]
It appears that we are no longer able to handle design matrices that are data frames, as seen from the R-output below:
```R> n = 100; p = 5
> X = data.frame(matrix(rnorm(n*p), n, p))
> Y = rnorm(n)
> rf = regression_forest(X, Y)
Error in data.frame(..., check.names = FALSE) : 
  arguments imply differing number of rows: 100, 0

> rf = regression_forest(as.matrix(X), Y)
> print(rf)
GRF forest object of type regression_forest 
Number of trees:  2000 
Number of training samples: 100 
Variable importance: 
    1     2     3     4     5 
0.351 0.171 0.136 0.186 0.156 
```

**Comment by halflearned** [comment]
I was just staring at this bug in my branch, thinking it was something I had done.

The culprit is [this line](https://github.com/grf-labs/grf/blob/62d925cbe3f2ebfdc225e6d014fadc62d02ba030/r-package/grf/R/input_utilities.R#L229). Apparently, we can `cbind` a matrix and a NULL (in which case the NULL is ignored), but not a data.frame and a NULL (in which case an error is raised). 

```
X1 <- data.frame(matrix(rnorm(n*p), n, p))
X2 <- as.matrix(X1)
sample.weights <- NULL
cbind(X1, sample.weights) # Bad!
cbind(X2, sample.weights) # Good (?!)
```
