### ISSUE TITLE
Categorical Variables and Clustering

### ISSUE THREAD

**Issue by Cresti** [grf-labs/grf#445]
Dear all, 

I am currently using causal forests for my analysis of firm level data. One important covariate, two digit industry code, is a categorical variable with almost 50 categories. I followed your advice from previous entries here and defined the categorical variable as numeric. The results are stable and look fine. However, when I am clustering with respect to the two-digit industry code (samples.per.cluster = 60), the results get stronger (especially for the average treatment effect) and the significance level increases (p.values fall from around 0.06 in the "normal" case to 0.02). Now I am a bit confused why it is so? 
Clustering has not only an effect on inference but also on the estimates (especially ATE).
Does clustering make it easier for the forest to handle variables with many categories?

Thank you very much for any suggestions!

**Comment by swager** [comment]
When clustering, we by default give equal weight to each cluster (see Section 1.2 of https://arxiv.org/pdf/1902.07409.pdf for a discussion). The reason we did this is to make sure SEs don't blow up if one cluster dominates all the others (since the forest might look completely different depending on whether or not the large cluster is sampled). When estimating the ATE, this may change the estimand, as in relative terms we now give more weight to observations in small clusters than in large clusters. If you don't like this behavior, you can manually up-weight large clusters using the `sample.weights` argument.

**Comment by hliebert** [comment]
What is the advantage of using `sample.weights` to setting `samples_per_cluster = max(table(clustervar))` ?

**Comment by swager** [comment]
Those two commands do different things:
- The `samples.per.cluster` argument captures how many units are drawn from each cluster when growing a tree. So, for example, if you cluster by village and set `samples_per_cluster = 10`, for each tree we'll first draw a sample of villages, then draw 10 people at random from each village, and then grow forest on the drawn people.
- The `sample.weights` argument is directly used in the prediction phase to modulate the importance of each unit. See #473 for more discussion of how we use it.
