### ISSUE TITLE
Exporting the treatment and control groups

### ISSUE THREAD

**Issue by ginward** [grf-labs/grf#486]
Hello, 

Is there a way to export the treatment and controlled subjects from the leaf nodes? 

Thanks,

Jinhua

**Comment by erikcs** [comment]
There is ongoing work on functionality related to this in #298 . What exactly are you after?

**Comment by erikcs** [comment]
To just query an arbitrary tree you can traverse the tree like [this](https://github.com/grf-labs/grf/blob/master/core/src/tree/Tree.cpp#L106) using the tree nodes stored in get_tree:

```R
find_leaf_node = function(tree, sample) {
  node = 1
  while (TRUE) {
    if (tree$nodes[[node]]$is_leaf)
      break()
    split_var = tree$nodes[[node]]$split_variable
    value = tree$nodes[[node]]$split_value
    if (value <= sample[split_var])
      node = tree$nodes[[node]]$left_child
    else
      node = tree$nodes[[node]]$right_child
  }
  node
}
```

```R
library(grf)
set.seed(123)
n = 200; p = 10
X = matrix(rnorm(n*p), n, p)
W = rbinom(n, 1, 0.4 + 0.2 * (X[,1] > 0))
Y = pmax(X[,1], 0) * W + X[,2] + pmin(X[,3], 0) + rnorm(n)
forest = causal_forest(X, Y, W)
tree = get_tree(forest, 1)

# The leaf nodes for all observations:
> head(sapply(1:n, function(i) find_leaf_node(tree, X[i, ])))
 1] 3 3 5 4 4 5

> tree$nodes # sample (C++ index) 134 is in leaf 5
[[5]]
[[5]]$is_leaf
[1] TRUE

[[5]]$samples
 [1] 134  18 111 155  21  38  63  23 168 176  55 180 106 118 143

> find_leaf_node(tree, X[134 - 1, ]) 
[1] 5
```
(this does not take OOB into account)

**Comment by ginward** [comment]
@erikcs Thanks for your kind response. I assume this is based on the information to construct the trees? i assume that, to get the node of the sample with the information to estimate treatment effect, all we need to do is use out-of-bag data for it? For example, in the above code, if we use the data not used by tree 1 to find the node, that is presumably the information used by grf to estimate treatment effects?

**Comment by erikcs** [comment]
@ginward OOB has nothing to do with "estimating" treatment effects, but predicting them for a new "unseen" sample. (but maybe this was already clear and is just semantics)

And I was a bit unclear before, sorry, I re-read the documentation for `get_tree` and forgot that it reports more granular information: With honesty on, it reports the samples used for repopulating the tree, i.e. providing the relevant estimates:

if you run

```R
set.seed(123)
n = 200; p = 5
X = matrix(rnorm(n*p), n, p)
W = rbinom(n, 1, 0.4 + 0.2 * (X[,1] > 0))
Y = pmax(X[,1], 0) * W + X[,2] + pmin(X[,3], 0) + rnorm(n)
forest = causal_forest(X, Y, W, seed = 123)
tree = get_tree(forest, 1)
```

then `tree$drawn_samples` will contain 100 samples since sample.fraction = 0.5

the leaf nodes are: 3, 4, 5. since honesty.fraction=0.5 the total length of 

tree$nodes[[3]]$samples
tree$nodes[[4]]$samples
tree$nodes[[5]]$samples

is 50, and these are the samples that went into the tree for repopulating the leaves (and the complement of these were used for determining splits), i.e. for providing the relevant estimates (treatment effect in cf, average Y in regression_forest)

Maybe @swager would like to chime in

Also, there is an extensive description of what grf does here: https://github.com/grf-labs/grf/blob/master/REFERENCE.md

Also some additions was made to tree visualization in 3ff436d
