### ISSUE TITLE
custom function in quantile regression forest

### ISSUE THREAD

**Issue by bryorsnef** [grf-labs/grf#588]
The implementations of the quantile regression forests in quantregForest and ranger allow for users to specify their own functions (such as sampling one point) over the conditional distribution, via the what argument of predict.quantregForest or predict.ranger. Could a similar option be implemented in grf?  

https://www.rdocumentation.org/packages/quantregForest/versions/1.3-7/topics/predict.quantregForest

**Comment by charliekirkwood** [comment]
Bumping this issue - it would be great to be able to access the predictive ecdf directly, rather than having to specify quantiles to predict.

As @bryorsnef points out, this can be done in quantregForest using e.g. the following code:

rf <- quantregForest(mtcars[,-1], mtcars$mpg)
pred <- predict(rf, mtcars[1,], what = function(x) ecdf(x))[[1]]
plot(pred)
![quantregForest ecdf](https://user-images.githubusercontent.com/21589762/73932080-72d2be00-48d1-11ea-8168-ae9940df6299.png)

Is the same possible in grf?

p.s. big fan of this package

**Comment by erikcs** [comment]
@bryorsnef @charliekirkwood you can access the adaptive forest weights (denoted alpha in the grf Annals of Statistics paper) through the [get_sample_weights](https://grf-labs.github.io/grf/reference/get_sample_weights.html) function and produce the kernel weighted estimates you desire. For example:

```R
library(grf)
library(Matrix) # `get_sample_weights` returns a sparse matrix
X = mtcars[, -1]
Y = mtcars$mpg
rf = regression_forest(X, Y)
weights = get_sample_weights(rf, X[1, ])

sum(weights * Y)
# [1] 21.20014
predict(rf, X[1,])$predictions
# [1] 21.20014

# Base R's `ecdf` does not support weights
# using `ewcdf` from the "spatstat" package instead:
# http://search.r-project.org/library/spatstat/html/ewcdf.html)
plot(spatstat::ewcdf(Y, as.vector(weights)))
```

![wecdf](https://user-images.githubusercontent.com/7185264/82631374-1e1a3100-9baa-11ea-9aea-a171b436f7e7.png)



(apologies for the late reply)

**Comment by erikcs** [comment]
If this was helpful for your question, we could perhaps add a similar example to the `get_sample_weights` docstring?
