### ISSUE TITLE
When using foret plot to  identifiy subgroups with heterogenous treatment effect, forest plot is not reproducible if seed No. is different

### ISSUE THREAD

**Issue by tianshengwang** [grf-labs/grf#607]
Dear GRF developers:
I'm using the 1.0.1 version on trial data to identifiy subgroups with heterogenous treatment effect. The following codes show that different forest plots (shown below) are gernerated by different seed No. 
```
n = 2000; p = 10
X = matrix(rnorm(n*p), n, p)
X.test = matrix(0, 101, p)
X.test[,1] = seq(-2, 2, length.out = 101)
W = rbinom(n, 1, 0.4 + 0.2 * (X[,1] > 0))
Y = pmax(X[,1], 0) * W + X[,2] + pmin(X[,3], 0) + rnorm(n)

tau.forest = causal_forest(X, Y, W, num.trees = 2000, min.node.size = 50, seed = 12345)
tree.plot = plot(get_tree(tau.forest, 1))
tree.plot
tau.forest2 = causal_forest(X, Y, W, num.trees = 2000, min.node.size = 50, seed = 678910)
tree.plot2 = plot(get_tree(tau.forest2, 1))
tree.plot2
```
So my questions are:
1) does the "index" parameter in get_tree(forest, index) function mean the ith tree generated? i.e. index=1 means the 1st tree, ... index=2000 means the 2000th tree 
2) is the inconsistency of the 2 forest plots below because "get_tree" can only retrieve a specific single tree (e.g. the 1st, or the 2000th) from a trained forest rather than the representative tree(the average of all trees or the "best tree" in the trained forest)? 
3) is there anyway to get the representative tree with GRF to make the forest plot reproducible? I know how to get it with randomForest, but not sure how to get it with GRF. 

![forest plot_12345](https://user-images.githubusercontent.com/40049497/72193688-93921b80-33d8-11ea-9fd2-c295c3f73f06.png)
![forest plot_678910](https://user-images.githubusercontent.com/40049497/72193695-98ef6600-33d8-11ea-8936-d9587d1ad7b1.png)

**Comment by swager** [comment]
Yes that's right: `get_tree` only returns the first tree generated by the forest, which is not in any sense guaranteed to be the best tree in the forest. In fact, forests explicitly try to grow many noisy trees and then achieve stability by averaging; so by design the first tree in the forest is expected to be noisy. The `get_tree` function is meant to be a diagnostic function for understanding what's going on inside the forest; not something for getting a summary of the forest.

If you want something more stable, you could try the (experimental) find best tree script in #281, or you could try the policyTree functions in https://github.com/grf-labs/policyTree.

**Comment by tianshengwang** [comment]
> Yes that's right: `get_tree` only returns the first tree generated by the forest, which is not in any sense guaranteed to be the best tree in the forest. In fact, forests explicitly try to grow many noisy trees and then achieve stability by averaging; so by design the first tree in the forest is expected to be noisy. The `get_tree` function is meant to be a diagnostic function for understanding what's going on inside the forest; not something for getting a summary of the forest.
> 
> If you want something more stable, you could try the (experimental) find best tree script in #281, or you could try the policyTree functions in https://github.com/grf-labs/policyTree.

@swager Thanks! Both best_tree and polyTree (opt.tree) work, but it seems the best tree (or opt.tree) shape still depends on the seed number, i.e. subgroup stratification decision is not very reproducible (example show below). My goal is to split population to find subgroup with heterogeneous treatment effect, then peform analysis to assess risk difference, risk ratio in each subgroup identified by the best_tree or opt.tree. Do you have any suggestions?
```
n = 2000; p = 10
X = matrix(rnorm(n*p), n, p)
X.test = matrix(0, 101, p)
X.test[,1] = seq(-2, 2, length.out = 101)
W = rbinom(n, 1, 0.4 + 0.2 * (X[,1] > 0))
Y = pmax(X[,1], 0) * W + X[,2] + pmin(X[,3], 0) + rnorm(n)
tau.forest = causal_forest(X, Y, W, num.trees = 4000, min.node.size = 50, seed = 12345)
best_tree_info <- find_best_tree(tau.forest, "causal")
best_tree_info$best_tree
tree.plot = plot(get_tree(tau.forest, best_tree_info$best_tree))
tree.plot
tau.forest2 = causal_forest(X, Y, W, num.trees = 4000, min.node.size = 50, seed = 678910)
best_tree_info2 <- find_best_tree(tau.forest2, "causal")
best_tree_info2$best_tree
tree.plot2 = plot(get_tree(tau.forest2, best_tree_info2$best_tree))
tree.plot2
```
tree.plot by seed=12345
![Best_tree12345](https://user-images.githubusercontent.com/40049497/72686294-12661300-3ac1-11ea-94e9-70bac25c5536.png)
tree.plot by seed=678910
![Best_tree678910](https://user-images.githubusercontent.com/40049497/72686298-1d20a800-3ac1-11ea-9da2-b4887949ac49.png)

**Comment by swager** [comment]
Single trees are notoriously quite unstable -- and that observation is in fact a big part of why people like forests! (Because you get to average out the randomness of tree search.)

Whenever using a single tree, it's important to remember that one only gets one (hopefully good) representation of heterogeneity, but not the only good tree-shaped representation of heterogeneity.

**Comment by tianshengwang** [comment]
@swager Thanks!
