### ISSUE TITLE
fixed effect and clustered standard errors

### ISSUE THREAD

**Issue by zhong1969** [grf-labs/grf#631]
My question is to apply “instrumental_forest” and “regression_forest” to a dataset for which my original method is panel fixed-effect model or difference-in-difference model.
 
In both “instrumental_forest” and “regression_forest”, we have “clusters=” option. If I set “clusters=school.id”. Doing so, have we reached both the purpose of controlling school fixed effects and the purpose of obtaining standard errors clustered at school level? If not, how could I reach the following different purposes?
 
1.      Controlling school fixed effects only.
2.      Controlling school fixed effects and obtaining standard errors clustered at school level.
3.      Controlling school fixed effects and obtaining standard errors clustered at higher level (say, city level).
 
Thanks!

**Comment by erikcs** [comment]
@zhong1969 here is an earlier question that might be useful: #532

**Comment by swager** [comment]
Yes exactly. The cluster argument is about standard errors, i.e., SEs are computed as though we were drawing clusters (as opposed to units) at random. Controlling for a categorical variable in a forest is trickier; one possible solution is to use https://arxiv.org/pdf/1908.09874.pdf.

Finally -- and this is a nitpick, but I'm only bringing it up because it highlights why this is not an obvious problem -- "controlling for school fixed effects" doesn't necessarily make sense non-parametrically, because a fixed effect is essentially by definition a parameter in a linear model. Unless, of course the goal is to fit an additive model of the type E[Y | X = x, School = j] = f(x) + alpha_j, and so now we've introduced fixed effects alpha_j again. But the most general way to control for school is to assume E[Y | X = x, School = j] = f(x, j), and there are no "fixed effects" here.

**Comment by zhong1969** [comment]
Dear Professor Wager:

Thanks again. Related to fixed effect and your paper “Sufficient Representations for Categorical Variables”.

How should we handle other dummy control? For example, should we “mean code” those dummy controls as we do regarding continuous controls?

Best regards,

Zhong

发件人: Stefan Wager [mailto:notifications@github.com]
发送时间: 2020年3月19日 0:40
收件人: grf-labs/grf <grf@noreply.github.com>
抄送: zhong1969 <zhong1969@hotmail.com>; Mention <mention@noreply.github.com>
主题: Re: [grf-labs/grf] fixed effect and clustered standard errors (#631)


Yes exactly. The cluster argument is about standard errors, i.e., SEs are computed as though we were drawing clusters (as opposed to units) at random. Controlling for a categorical variable in a forest is trickier; one possible solution is to use https://arxiv.org/pdf/1908.09874.pdf.

Finally -- and this is a nitpick, but I'm only bringing it up because it highlights why this is not an obvious problem -- "controlling for school fixed effects" doesn't necessarily make sense non-parametrically, because a fixed effect is essentially by definition a parameter in a linear model. Unless, of course the goal is to fit an additive model of the type E[Y | X = x, School = j] = f(x) + alpha_j, and so now we've introduced fixed effects alpha_j again. But the most general way to control for school is to assume E[Y | X = x, School = j] = f(x, j), and there are no "fixed effects" here.
