### ISSUE TITLE
Results from average_partial_effect and best_linear_projection do not coincide

### ISSUE THREAD

**Issue by gcasamat** [grf-labs/grf#638]
I have grown a causal forest with a continuous treatment. 
From reading the comments in the best_linear_projection function script, I thought that it should return the average partial effect when no covariates are specified: "The case of the null model tau(Xi) ~ beta_0 is equivalent to fitting an average treatment effect via AIPW". I however obtain distinct results from the average_partial_effect and best_linear_projection functions.

Here is my code (I could provide the data if necessary): 
```
cf.test <-  causal_forest(X, Y, W,
                     clusters = data_for_reg$codiris_num)
average_partial_effect(cf.test,calibrate.weights = FALSE)
 estimate    std.err 
0.10775921 0.01939295 
best_linear_projection(cf.test)
Best linear projection of the conditional average treatment effect.
Confidence intervals are cluster- and heteroskedasticity-robust (HC3):

             Estimate Std. Error t value  Pr(>|t|)    
(Intercept) 0.1248914  0.0094074  13.276 < 2.2e-16 ***
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1
```

Thanks for your help!

**Comment by erikcs** [comment]
There is some randomness arising from the variance term in `debiasing.weights` being estimated by two different regression forests internally.

With #637 you can supply `debiasing.weights` to both `average_partial_effect` and `best_linear_projection` and compare:

```
n <- 500
p <- 10
X <- matrix(rnorm(n * p), n, p)
W <- rbinom(n, 1, 1 / (1 + exp(-X[, 2]))) + rnorm(n)
Y <- pmax(X[, 1], 0) * W + X[, 2] + pmin(X[, 3], 0) + rnorm(n)
cf <- causal_forest(X, Y, W)

average_partial_effect(cf, debiasing.weights = rep(1, n), calibrate.weights = FALSE)
# estimate    std.err 
# 0.33262107 0.04968218 
best_linear_projection(cf, debiasing.weights = rep(1, n))
#            Estimate Std. Error t value  Pr(>|t|)    
# (Intercept) 0.332621   0.055209  6.0247 3.292e-09 ***
```

As you see when `debiasing.weights` are the same, the point estimates are the same (up to rounding), but the standard error may differ, because `best_linear_projection` computes them with `lmtest::coeftest`.

**Comment by swager** [comment]
Yes ideally the SEs should be exactly (or very nearly) the same. We should understand why the SEs are different by as much as 10% here.

**Comment by erikcs** [comment]
Here's a reproducible example with clustering that highlights the sometimes big SE difference

```
set.seed(123)
n <- 500
p <- 10
X <- matrix(rnorm(n * p), n, p)
W <- rbinom(n, 1, 1 / (1 + exp(-X[, 2]))) + rnorm(n)
Y <- pmax(X[, 1], 0) * W + X[, 2] + pmin(X[, 3], 0) + rnorm(n)
cf <- causal_forest(X, Y, W, clusters = sample(1:2, n, replace = TRUE), seed = 123)

average_partial_effect(cf, debiasing.weights = rep(1, n), calibrate.weights = FALSE)
# estimate   std.err 
# 0.2341164 0.2510048

best_linear_projection(cf, debiasing.weights = rep(1, n))
#             Estimate Std. Error t value Pr(>|t|)
# (Intercept)  0.23412    0.40057  0.5845   0.5592
```

**Comment by gcasamat** [comment]
Many thanks for your reactions. 
I looked at the scripts of the two functions and the only difference for the estimation of the treatment variance is the option ci.group.size = 1 in the best_linear_projection script:
variance.forest <- regression_forest(subset.X.orig,
                                        (subset.W.orig - subset.W.hat)^2,
                                        clusters = subset.clusters,
                                        num.trees = num.trees.for.variance,
                                        ci.group.size = 1)
Is this it that explain the difference?
At a broader level, I am curious to know if there is some criterion to choose whether to use debiasing weights equal to 1 or the ones built in the function average_partial_effect?

**Comment by erikcs** [comment]
`ci.group.size` is one in both functions now (it does not matter for forest predictions, it is only related to [variance estimates](https://grf-labs.github.io/grf/REFERENCE.html#variance-estimates), which are not needed here)

And `debiasing.weights = rep(1, n)` was just an example thrown together to see that only standard errors differed between those two functions (because of `lmtest`). Using the built in `debiasing.weights` means that grf calculates estimates using the doubly robust approach (https://arxiv.org/pdf/1902.07409.pdf)

**Comment by erikcs** [comment]
Let us also aim to address #644 in the future PR that resolves this.

**Comment by erikcs** [comment]
Just a thought for part of the future consolidation of summary functions: it could maybe be convenient to have `predict` take an optional argument allowing for returning double robust scores for the given forest (forests that require compliance scores etc, and subsets, need more thought).
