### ISSUE TITLE
Sample splits and parameter tuning

### ISSUE THREAD

**Issue by philippschmalen** [grf-labs/grf#646]
I have a question about data sampling for training, tuning and testing. If I understood the method correctly, I can provide data to the causal_forest() method without splitting it beforehand into a train and test set. Out-of-bag prediction ensures that different observations are used for training and prediction. But what if parameter tuning is enabled? Does the tuning procedure ensure that observations already used for training are not used for tuning? 
Splitting the data into train-tune-test sets would follow the concept of nested cross-validation (distinct samples for training, tuning/validation and estimation/prediction). 

Just to be sure: `sample.fraction` controls the share used for training (=choosing splits, growing trees), whereas `honesty.fraction` controls the share of `sample.fraction` data to separate between choosing splits and making predictions. For the case of parameter tuning, I could not find any hint in the docs about another split, where parts of the data are distinctly used to train, find optimal parameters and predict, like in nested-cross-validation.  But maybe I am on the wrong track, since causal forest follows a different objective than "plain" outcome prediction. It is not primarily concerned with the accuracy to predict outcomes, but treatment effect estimation. Therefore, I would be grateful for any further info about parameter tuning, sample splits or where to look for their implementation. 

Running on R3.6.3 and GRF 1.1.0.

**Comment by erikcs** [comment]
Here is how [tuning](https://github.com/grf-labs/grf/blob/master/r-package/grf/R/tuning.R) works:

Input: full data, `X`, `Y`, `num.fit.reps`, `num.fit.trees`, `num.optimize.reps`

Say we want to tune `mtry` for a regression forest. 

1) Draw `num.fit.reps` uniform (0,1) random variables (`Xmtry`)

2) Transform these to an appropriate parameter range, in the case of `mtry`: (0, 1) -> (1, ncol(X)), then fit a regression forest to (X,Y), using `num.fit.trees`, with each of the `num.fit.reps` different `mtry`s. 

3) Predict the OOB debiased error `Yerror` (the `debiased.error` attribute in a saved forest) for each of the forests. This is a forest prediction [error](https://github.com/grf-labs/grf/blob/master/core/src/prediction/RegressionPredictionStrategy.cpp#L122) estimate with a bias adjustment for the small number of trees (`num.fit.trees`) used to fit the forest. A small number of trees is used to make tuning computationally feasible. 

4) We now have a forest error vector of length `num.fit.trees` for the random draws of `mtry`s. Fit a flexible model to these error estimates as a function of the different `mtrys`s: `Yerror = f(Xmtry)`. grf does this with a gaussian process using the `DiceKringing` package. 

5) To find the optimal `mtry`: use the fitted error model above to predict errors for a large number (`num.optimize.reps`) of different values for `mtry`. Then select the `mtry` that was associated with the smallest error, this is an estimate of the optimal `mtry`.

The procedure is the same of you want to tune a matrix of parameters, for example ([`mtry, `min.node.size`], or a different forest, like a causal forest. Note that there is not a lot of strong theory to guide random forest tuning, and  theoretical properties wrt. to different parameters. The procedure above is something that turns out to work reasonably well in practice.

It can be summarized as a random grid search, where you approximate the grid surface with a gaussian process.

**Comment by jtibshirani** [comment]
@philippschmalen the [algorithm guide](https://github.com/grf-labs/grf/blob/master/REFERENCE.md) might be a helpful reference for you. If there are aspects that are unclear or missing in the reference, let us know and we can try to fill in the gaps.

**Comment by philippschmalen** [comment]
Thanks for the immediate response and for clarifying the procedure behind parameter tuning. Your support is truly amazing! 
I indeed consulted the algorithm reference, which is an excellent resource to complement the code and papers. However, it lacks information on whether data is split into train-validate-test sets, as it is common in parameter tuning for models that focus solely on outcome prediction, i.e. prediction accuracy. 

To summarize my insights on parameter tuning for causal forest:

* draw `tune.num.reps` parameter sets from a range of possible parameter values 
* use the full data to train mini-causal forests that have `tune.num.trees` trees for each parameter set
* assign observations to causal trees not already used for training (out-of-bag) to predict *Y* and compute the `debiased.error`
* do this for each parameter set to obtain error measures
* fit a flexible model to predict which `tune.num.draws` parameter sets minimize `debiased.error` 
* those parameters that minimize the predicted error are used to specify the final causal forest model 

My point is, that the same observations used to determine optimal model parameters are later used to train the causal forest and predict treatment effects, i.e. for two purposes. Thus, they would loose the property of being "out-of-bag", at least when requiring distinct samples for training, tuning and prediction. However, causal forest's objective is to estimate treatment effects (minimize bias) instead of predicting outcomes (minimize prediction error). Due to these distinct objectives, the implemented parameter tuning may suffice to provide a model that is reasonably accurate, computationally feasible and has a low bias. 
But, I might be wrong in describing it this way and appreciate your feedback!
