### ISSUE TITLE
poor overlap or compliance in instrumental forest + low R-squared in best linear projection

### ISSUE THREAD

**Issue by fjfzclcxj** [grf-labs/grf#724]
Hi, 

Thank you for the awesome package, but I'm a little confused when using average effect estimation or best linear projections in instrumental forest:

- Question 1

These two tasks both need to calculate doubly robust score, if I understand them correctly. 

But with poor overlap or compliance score, according to the weighting formula in [Athey, Susan, and Stefan Wager. "Efficient policy learning." arXiv preprint arXiv:1702.02896 (2017)](https://arxiv.org/pdf/1702.02896v4.pdf), the weighting function g(·) will explode. As a result, doubly robust score of some sample will be quite large, and **R-squared of best linear projection is around 1e-5, which seems to be too low**.

So I wonder **is there any method similar to average_treatment_effect(target.sample='overlap') for instrumental forest?** 

And I think even in causal forest, there is no solution for best linear projection with poor overlap. Then **what should we do when confronted with such circumstances if we want to do regression? Is just using tau.hat as dependent variable appropriate?**

![image](https://user-images.githubusercontent.com/10251203/91167289-4adc6800-e706-11ea-96e2-2538402957c9.png)

- Question 2

When comparing the code of average_treatment_effect(target.sample='overlap') with [Li, Morgan, and Zaslavsky "Balancing covariates via propensity score weighting" JASA (2017)](http://www.personal.psu.edu/klm47/LockMorgan_Methodology_2017.pdf), **I'm a little confused: I thought we need to use overlap weight to reweight doubly robust score (weight.1 = 1 - W.hat, weight.0 = W.hat), but as the code says, we only need to do a regression? Am I missing any point?**

![image](https://user-images.githubusercontent.com/10251203/91170265-351d7180-e70b-11ea-9e56-04a9dc8be317.png)

```R
if (target.sample == "overlap") {
    W.residual <- subset.W.orig - subset.W.hat
    Y.residual <- subset.Y.orig - subset.Y.hat
    tau.ols <- lm(Y.residual ~ W.residual, weights = subset.weights)
    tau.est <- coef(summary(tau.ols))[2, 1]
    if (cluster.se) {
      tau.se <- sqrt(sandwich::vcovCL(tau.ols, cluster = subset.clusters)[2, 2])
    } else {
      tau.se <- sqrt(sandwich::vcovHC(tau.ols)[2, 2])
    }
    return(c(estimate = tau.est, std.err = tau.se))
  }
```

Any help is appreciated

Andrew Chen

**Comment by swager** [comment]
For Q1, the issue #716 discusses overlap for the IV case. Meanwhile, for best linear predictions, that's right -- we don't currently have an option that works with poor overlap. One way around this would be to follow the strategy of:

Crump, R. K., Hotz, V. J., Imbens, G. W., & Mitnik, O. A. (2009). Dealing with limited overlap in estimation of average treatment effects. Biometrika, 96(1), 187-199.

You could, say, subset on all observations with propensity score between 0.1 and 0.9, and then run BLP on those.

For the second point: One can check that the residual on residual regression estimator converges to the overlap-weighted estimand of Li & al. And it turns out that the residual on residual regression is a good algorithm (and estimator) for getting at this target. [For intuition, note that the residual-on-residual estimator is usually thought of as a tool for estimating a constant treatment effect parameter. Meanwhile, the estimand of Li & al is, under heterogeneity, the weighted treatment effect that can be estimated with minimal variance. So then the question is: What does the natural constant treatment effect estimator target under heterogeneity? It turns out that it targets a weighted treatment effect -- and, given this, it's not surprising that it in fact targets the weighted treatment effect that can be estimated with minimal variance, i.e., the estimand of Li & al.]

**Comment by fjfzclcxj** [comment]
Thank you for your early reply!

I thought another work around: just take W.hat = 0.5 for each sample (after all, it's a random experiment with treatment:control = 1:1), then there is no poor overlap; 

But I still met with the same issue: 

for lm(tau.hat ~ ., data=X_for_forest), I have R-squared around 0.1
for lm(dr.score ~ ., data=X_for_forest), I have R-squared around 1e-5

So I wonder **it's ok to just use tau.hat as DV for regression or use it for average treatment effect estimation**? (Of course, **I'm not sure what standard error estimation we should use if just taking tau.hat when dealing with these two estimation**)  

Or to say, what's the advantage of using dr.score over using tau.hat? After all, if I understand it correctly, in [Athey, S., Tibshirani, J., & Wager, S. (2019). Generalized random forests. The Annals of Statistics, 47(2), 1148-1178](https://arxiv.org/pdf/1610.01271.pdf), there is only empirical guarantee for normality of tau.hat. Maybe using tau.hat or dr.score is just an empirical issue? 

Apologize in advance if I misunderstand anything. Thank you for your time.

**Comment by swager** [comment]
Sorry, I missed the question about the R-squared. So first, as to the definition of the BLP: It's the best linear approximation to the true CATE function in terms of some covariates A. Specifically, if you write the CATE as tau(x) = E[Y(1) - Y(0) | X = x], then the BLP has coefficients beta, where

beta = argmin{E[(tau(X) - A beta)^2]}.

If you knew the true tau(X), then estimating beta would be easy: just regress tau(X) against A. But here you don't know the true tau(X) -- you only have an estimate -- and that's where the situation gets statistically interesting. In particular, regressing the causal forest estimates \hat{\tau}(X) against A is not necessarily a good estimate of \beta.

The cool result about BLP regression (see the referenced paper by Chernozhukov and Semenova for more discussion) is that the following simple estimator is a good estimator of beta under general conditions: First form the appropriate DR scores, and then regress those DR scores against A. The guarantees you get from this are that:
- The resulting point estimates \hat{\beta} are accurate, and
- The standard errors (and p-values) accurately capture the sampling variability of the whole procedure (including the initial causal forest fitting stage).

Now, despite those results, one should note that the regression of DR scores against A is not quite a usual regression that can be interpreted as a prediction problem -- it was a regression that was constructed to give you good estimates of \beta. And one way this weirdness manifests itself is that the R-squared coefficient is really low. This is normal, and you shouldn't worry about it. What a low R-squared tells you is that it's very very hard to predict the DR scores from A -- and that's true! But that's not what we're trying to do. Because it turns out that regressing DR scores against A, despite not having a good R-squared, still gives you good estimates of beta.

Now, if you want is something that captures the ability of this linear projection to capture the true signal, e.g., an estimate of Var[A\beta] / Var[tau(X)], that's a meaningful question -- but a hard one to answer robustly. If that's what you're interested in, happy to continue the conversation.

**Comment by fjfzclcxj** [comment]
Thank you so much for your simple but profound explanation!

Yes, what I need is a good estimate of \beta, the estimate of Var[A\beta] / Var[tau(X)] may be beyond my capability for now lol.

And there's a last question: in instrumental forest, how can we do best linear projection with poor compliance? It seems that [Crump, R. K., Hotz, V. J., Imbens, G. W., & Mitnik, O. A. (2009). Dealing with limited overlap in estimation of average treatment effects. Biometrika, 96(1), 187-199.](https://dash.harvard.edu/bitstream/handle/1/3007645/imbens_addressing.pdf) doesn't give guarantee for poor compliance? 

Best Regards

**Comment by swager** [comment]
The question of what to do in this kind of analyses in the IV setting with locally poor compliance hasn't received much attention in the literature. #716 has some further discussion.

**Comment by fjfzclcxj** [comment]
Ok thanks! I will close the issue for now~
