### ISSUE TITLE
Parametric Orthogonalization

### ISSUE THREAD

**Issue by hhsievertsen** [grf-labs/grf#800]
Hi Team,

thank you for developing a great resource! 

I have a tiny **question**: Is it meaningful to use a parametric approach for the orthogonalization? I.e. for example a 2way FE OLS like in the following example:

```{r}
set.seed(1909)

library("grf")
library("fixest")

# Dummy data for example
N=1000
T=20
X1=rnorm(N*T)
X2=rnorm(N*T)
X3=round(runif(N*T))
state_fe=as.integer(rep(sample(1:50,N,replace=T),T))
year_fe=as.integer(rep(1990:2009,each=N))
W=round(runif(N*T))
Y=5+0.2*X1-0.1*X2+0.5*W-0.5*(X3==1)*W+0.4*state_fe-0.4*year_fe+rnorm(N*T)
df=data.frame(Y=Y,X1=X1,X2=X2,X3=X3,state_fe=state_fe,year_fe,W=W)

# Orthogonalize
m1<-feols(Y~X1+X2|state_fe+year_fe,df)
Y.hat<-predict(m1)
m2<-feols(W~X1+X2|state_fe+year_fe,df)
W.hat<-predict(m2)

# Estimate Causal Forest
cf <- causal_forest(
  X = as.matrix(X1,X2,X3),
  Y = Y,
  W = W,
  Y.hat=Y.hat,
  W.hat=W.hat,
  num.trees=50)

# Average treatment effect
average_treatment_effect(cf)
```

Thanks a lot!
Hans

**Comment by swager** [comment]
Hi @hhsievertsen, the short answer is yes -- you can use any method you want for orthogonalization. The intuition behind this orthogonalization step is the same as in the Chernozhukov & al "double machine learning" paper, where they advocate orthogonalizing using the most accurate machine learning method available.

One thing to consider, though, is that in general one would want to use cross-fitting for the nuisance components to avoid own-observation bias. At the same time, the recommendation to use cross-fitting is a fairly conservative one, and in general one can get away without using cross fitting if one uses simple models for the nuisance components (like OLS). Where this leaves us with the above example is not 100% clear to me, though: On the one hand, you're using OLS (which suggests cross-fitting may not be needed), but on the other hand, you have a high-dimensional OLS model (due to the FEs), which may result in concerns about own-observation bias after all. How one would want to do cross-fitting with panel data is also something of a delicate question: Depending on the assumed dependence structure, it may make sense to hold out either cells or whole rows for the purpose of cross-fitting.

**Comment by hhsievertsen** [comment]
Thanks for the super fast response. That is very helpful. Good point about the cross-fitting.
Thanks!
