### ISSUE TITLE
Clarification about estimated individual treatment effects and second stage analysis

### ISSUE THREAD

**Issue by weim-mkt** [grf-labs/grf#808]
Dear authors,

I read several applied working papers on SSRN that use causal forests. These papers argue that they are able to use causal forest to estimate treatment effects for each individual. And then in the second stage regression, they regress the estimated individual treatment effects on individual-specific characteristics to investigate how these characteristics affect the treatment effects.

For the above application, I have some clarification questions:

1. After training causal_forest(X,Y,W), we can indeed make predictions for each individual in the training data using predict(cf_object,estimate.variance= T). However, can we really interpret these predicted values as the estimated individual-specific treatment effects and use them as the dependent variable in a second stage regression?
2. From the estimated variance, some individual treatment effects may not be statistically significant, should we interpret these insignificant predictions as 'no treatment effect' or 'we don't know because of statistical insignificance'?
3. If we can indeed bring predicted individual treatment effects into a second stage regression, should we drop those statistically insignificant individuals?

I have gone through previous posts but seem unable to find the answers. My apologies if I have missed answers from any previous posts. Looking forward to your reply. Many thanks!

**Comment by erikcs** [comment]
Hi @HarryMayday,

1:
a) Yes, `predict(forest)` returns estimates of tau(x) = E[Y(1) - Y(0) | X = x].
b) No, it is better to regress an updated score on X than direct estimates of tau(x) on X, this is available in [best_linear_projection](https://grf-labs.github.io/grf/reference/best_linear_projection.html). Below is an example showing how the estimate for beta1 in tau(X) = a + beta1 X1 + beta2 X2 + ... is biased if you do the plain linear regression (section 3.2/Figure 2 in https://arxiv.org/pdf/2001.09887.pdf also has a section on this - if you check back again in a few weeks when the latest draft is uploaded, maybe later in March).

```R
library(grf)
res.sim <- replicate(250, {
  n <- 500
  p <- 5
  X <- matrix(rnorm(n * p), n, p)
  W <- rbinom(n, 1, 0.5)
  Y <- pmax(X[, 1], 0) * W + X[, 2] + pmin(X[, 3], 0) + rnorm(n)
  forest <- causal_forest(X, Y, W)
  tau.hat <- predict(forest)$predictions
  tau.hat.ols <- lm(tau.hat ~ X)
  blp <- best_linear_projection(forest, X)
  c(blp[2,1], tau.hat.ols$coefficients[2])
})

n <- 20000
p <- 5
X <- matrix(rnorm(n * p), n, p)
W <- rbinom(n, 1, 0.5)
tau <- pmax(X[, 1], 0)
beta1.true <- lm(tau ~ X)$coef[2]

hist(res.sim[1, ], col = rgb(0,0,0,1/4), xlim = c(0, 0.9), main = 'Histogram of beta1')
hist(res.sim[2, ], col = rgb(1,0,0,1/4), add = TRUE)
abline(v = beta1.true, col = 'red')
```
The gray shaded histogram is the best linear projection estimates (which gives you valid standard errors), and the pink OLS on tau.hat, the true beta1 is highlighted with a red line.
![Screen Shot 2021-02-22 at 15 12 02](https://user-images.githubusercontent.com/7185264/108783361-3399fe00-7522-11eb-9317-cdcf2b0eb590.png)

2. As with any estimator, just because you fail to detect an effect, does not mean that one isn't present, and vice versa. Getting accurate pointwise predictions can be challenging, and the width of the confidence interval may be an indicator of this
