### ISSUE TITLE
Problems with install from source using devtools

### ISSUE THREAD

**Issue by UserMKR** [grf-labs/grf#838]
Hey there,
I would like to install the recent version of the grf package directly from source. I did this one year ago and it worked perfectly.
However, using R 4.0.0 and Rtools40 (x64) under Windows 10, I cannot install the new version. I also installed clang.
Installing the old version still works, however.
Is this a problem on my side or may there be a problem in the code?

Do you need more information?

Kind regards

**Comment by erikcs** [comment]
Hi @UserMKR, this is most likely because on Windows, devtools does not properly download git repos that uses symlinks. There is a Windows note [here](https://grf-labs.github.io/grf/DEVELOPING.html#note-for-windows-users) for an alternative.

If you just wish to install the latest master version as of day, I've also attached the latest tarball here

[grf_1.2.0.0_cd8909e tar.gz](https://github.com/grf-labs/grf/files/6152102/grf_1.2.0.0_cd8909e.tar.gz)

which you can install with

```
install.packages("https://github.com/grf-labs/grf/files/6152102/grf_1.2.0.0_cd8909e.tar.gz", repos = NULL, type = "source")
```

**Comment by CrystalXuR** [comment]
Hi @UserMKR, I am able to install the development version with devtools as follows: 
1. Open the terminal and find the path to R.exe or Rscript.exe
2. Run R.exe from the command line, then you enter an R terminal. e.g., C:\Program Files\R\R-4.1.1\bin>R.exe
3. Type "devtools::install_github("erikcs/grf", subdir = "r-package/grf", ref = "csf-prob")"
